# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Research"
  url = "/about"
  weight = 10
  identifier = "Research"

[[main]]
  name = "Overview"
  url = "/about#intro"
  weight = 10
  parent = "Research"

[[main]]
  name = "Projects"
  url = "/about#projects"
  weight = 20
  parent = "Research"

# Belongs to people menu
[[main]]
  name = "Team"
  url = "/about#people"
  weight = 20
  identifier = "People"

# Belongs to people menu
[[main]]
  name = "PI"
  url = "/authors/leo"
  weight = 10
  parent = "People"

# Belongs to people menu
[[main]]
  name = "members"
  url = "/about/#people"
  weight = 20
  parent = "People"

[[main]]
  name = "Publications"
  url = "/publication"
  weight = 50

[[main]]
  name = "Resources"
  weight = 60
  identifier = "Resources"

[[main]]
  name = "Lab Handbook"
  url = "/handbook"
  weight = 60
  parent = "Resources"

[[main]]
  name = "Join"
  url = "/join"
  weight = 70

# [[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
